name: Flask API #Nameing our Workflow

on: #This is our Trigger
  push:
    branches: [main, master]

jobs:

  build:
    runs-on: ubuntu-latest #Highly used Linux distribution, that is heavily support with user commands

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2 #Checks code for glaring errors

      - name: Set up Python
        uses: actions/setup-python@v2 #Sets up our python
        with:
          python-version: 3.12

      - name: Create Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Printing debugging Information
        run: |
          echo "Python Version: $(python --version)"
          echo "Working Directory: $(pwd)"
          echo "Content of Working Directory: $(ls-l)"
          echo "Contents of site-package: $(ls-l venv/lib/python*/site-packages)"
    
  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2 #Checks code for glaring errors

      - name: Set up Python
        uses: actions/setup-python@v2 #Sets up our python
        with:
          python-version: 3.12

      - name: Create Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover -s tests -p 'test_*'.py #Find my test files in my test folders using pattern 'test_<anything>.py'